#!/bin/bash

chown -R tomcat7:tomcat7 /var/log/tomcat7
/etc/init.d/tomcat7 start

# The container will run as long as the script is running, that's why
# we need something long-lived here
exec tail -f /var/log/tomcat7/catalina.out